language: node_js

node_js:
  - 10

script:
  - npm run lint
  - npm run test

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release
        on:
            branch: 'master'